### ISSUE TITLE
Problem at/around the foot of the download page

### ISSUE THREAD

**Issue by grahamperrin** [nomadbsd/website#15]
At the foot of <https://nomadbsd.org/download.html>: 

![image](https://user-images.githubusercontent.com/192271/191578439-ce09dc9a-b6d2-40f3-b8d6-2b1412137f40.png)

If it helps to understand the issue: there are multiple `#footer` anchors.

**Comment by mmertgunduz** [comment]
Hello @grahamperrin,

Thanks for letting us know, I'm started working on the issue.

Thanks for assigning @mrclksr.

**Comment by mmertgunduz** [comment]
Hey @mrclksr,

Everything works fine on my computer, can you try in your localhost too?

**Comment by mrclksr** [comment]
The local `download.html` does not have multiple footers. There was an older version of the file on our web server. For some mysterious reason, I had to delete all *.html files from the server, and then upload them, instead of just copying them over. Might be a bug in sshfs.

Anyway, problem should be fixed.

**Comment by mmertgunduz** [comment]
Ah, very strange. I checked the website, it is working now :-)

Nice job @mrclksr!

**Comment by grahamperrin** [comment]
Fix confirmed, thanks!
